### ISSUE TITLE
ansi_term deprecated

### ISSUE THREAD

**Issue by ggilley** [rajivr/fdb-wip#1]
Looks like ansi_term has been deprecated. I think bind_gen needs to be updated?

Crate:     ansi_term
Version:   0.12.1
Warning:   unmaintained
Title:     ansi_term is Unmaintained
Date:      2021-08-18
ID:        RUSTSEC-2021-0139
URL:       https://rustsec.org/advisories/RUSTSEC-2021-0139
Dependency tree:
ansi_term 0.12.1
└── clap 2.34.0
    └── bindgen 0.59.2
        └── fdb-sys 0.4.0
            └── fdb 0.4.0

**Comment by rajivr** [comment]
Thanks for the heads up! I'll check and update it.

**Comment by rajivr** [comment]
I've updated `bindgen` to `0.69.2`. Please check if it fixes the issue for you.

**Comment by ggilley** [comment]
That fixed it. Thanks!
